# --- General Settings ---
# Enable mouse support (clicking panes, resizing, scrolling)
set -g mouse on

# Set vi-mode for copy mode
setw -g mode-keys vi

# --- Key Bindings ---
# Scroll Up: Enter copy mode and jump 5 lines
bind -n WheelUpPane \
    if-shell -F -t = "#{mouse_any_flag}" \
        "send-keys -M" \
        "if -Ft= '#{pane_in_mode}' \
            'send-keys -X scroll-up; send-keys -X scroll-up; send-keys -X scroll-up; send-keys -X scroll-up; send-keys -X scroll-up' \
            'select-pane -t=; copy-mode -e; send-keys -X scroll-up; send-keys -X scroll-up; send-keys -X scroll-up; send-keys -X scroll-up; send-keys -X scroll-up'"

# Scroll Down: Jump 5 lines (exits mode automatically at bottom)
bind -n WheelDownPane \
    if-shell -F -t = "#{mouse_any_flag}" \
        "send-keys -M" \
        "if -Ft= '#{pane_in_mode}' \
            'send-keys -X scroll-down; send-keys -X scroll-down; send-keys -X scroll-down; send-keys -X scroll-down; send-keys -X scroll-down'"


# Make scrolling down exit copy mode automatically when you hit the bottom
bind -n WheelDownPane select-pane -t= \; send-keys -M

# v for begin selection (visual mode)
bind-key -T copy-mode-vi v send-keys -X begin-selection

# / for forward search and ? for reverse search
bind-key -T copy-mode-vi / command-prompt -i -p "search down" "send -X search-forward-incremental \"%%%\""
bind-key -T copy-mode-vi ? command-prompt -i -p "search up" "send -X search-backward-incremental \"%%%\""

# y for yank (copy) to BOTH tmux buffer and system clipboard
if-shell 'test "$(uname)" = "Darwin"' \
    'bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"' \
    'bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -in -selection clipboard"'

# Also copy to system clipboard when using the mouse to select
if-shell 'test "$(uname)" = "Darwin"' \
    'bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"' \
    'bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -in -selection clipboard"'

# --- Other ---
# Fix escape delay
set -sg escape-time 0

# Reload config file quickly
bind r source-file ~/.tmux.conf \; display "Config Reloaded!"
