# --- General Settings ---
setw -g mouse on
setw -g mode-keys vi
set -sg escape-time 0
set -g history-limit 50000

set-option -g prefix C-j
unbind C-b
bind-key C-j send-prefix
bind-key -n C-h previous-window
bind-key -n C-l next-window
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi / command-prompt -i -p "search down" "send -X search-forward-incremental \"%%%\""
bind-key -T copy-mode-vi ? command-prompt -i -p "search up" "send -X search-backward-incremental \"%%%\""

# Dynamic Clipboard Logic (macOS -> Wayland -> X11)
set -g @copy_cmd "if [ \"$(uname)\" = 'Darwin' ]; then pbcopy; elif command -v wl-copy > /dev/null; then wl-copy; else xclip -in -selection clipboard; fi"
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "#{@copy_cmd}"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "#{@copy_cmd}"

# --- Other ---
# Reload config file quickly
bind r source-file ~/.tmux.conf \; display "Config Reloaded!"

# --- Plugins ---
if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-logging'
set -g @plugin 'nhdaly/tmux-better-mouse-mode'

# --- Plugin Configuration ---
set -g @logging-path "$HOME/htb/logs"
set -g @screen-capture-path "$HOME/htb/logs"
set -g @save-complete-history-path "$HOME/htb/logs"

set -g @scroll-speed-num-lines-per-scroll 5
set -g @scroll-down-exit-copy-mode "on"
set -g @emulate-scroll-for-no-mouse-alternate-buffer "on"

run '~/.tmux/plugins/tpm/tpm'
